# The URL the site will be built for
base_url = "https://example.com"
theme = "hyde"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Michelle McDowell"
description= "Researcher in Risk and Evidence Communication"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here

hyde_links = [
    {url = "/research", name = "Research"},
    {url = "/tools", name = "Tools and Guides"},
    {url = "/publications", name = "Publications"},
    {url = "/talks", name = "Talks and Teaching"},
    {url = "/personal", name = "Personal"},

]
hyde_theme = "theme-base-08"